<?php

/**
 *
 * d8b  .d88888b. 88888888888     d8888 8888888b.
 * Y8P d88P" "Y88b    888        d88888 888  "Y88b
 *     888     888    888       d88P888 888    888
 * 888 888     888    888      d88P 888 888    888  .d88b.  888  888 .d8888b
 * 888 888     888    888     d88P  888 888    888 d8P  Y8b 888  888 88K
 * 888 888     888    888    d88P   888 888    888 88888888 Y88  88P "Y8888b.
 * 888 Y88b. .d88P    888   d8888888888 888  .d88P Y8b.      Y8bd8P       X88
 * 888  "Y88888P"     888  d88P     888 8888888P"   "Y8888    Y88P    88888P'
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with <plugin Name>.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author iOTADevs
 * @link http://iotadevs.github.io
 *
 */

declare(strict_types = 1);

namespace IOTADevs\Agent;

use CortexPE\utils\TextFormat;
use IOTADevs\Agent\entity\Agent;
use IOTADevs\Agent\entity\AutoAimBait;
use IOTADevs\Agent\handler\PacketHandler;
use IOTADevs\Agent\module\AgentModule;
use IOTADevs\Agent\module\AntiAutoAim;
use IOTADevs\Agent\module\AntiFly;
use IOTADevs\Agent\module\AntiNoClip;
use IOTADevs\Agent\task\AgentHeartbeat;
use pocketmine\entity\Entity;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase{
	/** @var Main */
	private static $instance;

	/** @var AgentModule[] */
	private $modules = [];

	/** @var array */
	public $configs = []; // yes this is an array. store the config values here...

	/** @var int[] */
	public $warnings = [];

	/** @var CompoundTag */
	private $agentSkin;

	/** @var AutoAimBait[] */
	public $baits = [];

	public function onEnable(){
		self::$instance = $this;

		@mkdir($this->getDataFolder());
		$this->saveDefaultConfig();
		$this->configs = $this->getConfig()->getAll();

		$pluginManager = $this->getServer()->getPluginManager();
		$pluginManager->registerEvents(new EventListener($this), $this);
		$pluginManager->registerEvents(new PacketHandler($this), $this);
		$this->getServer()->getScheduler()->scheduleRepeatingTask(new AgentHeartbeat($this), 5);

		$this->modules[] = new AntiFly();
		$this->modules[] = new AntiNoClip();
		$this->modules[] = new AntiAutoAim();

		Entity::registerEntity(AutoAimBait::class, true);
		Entity::registerEntity(Agent::class, true);

		$this->agentSkin = unserialize(base64_decode("TzozMDoicG9ja2V0bWluZVxuYnRcdGFnXENvbXBvdW5kVGFnIjo0OntzOjk6IgAqAF9fbmFtZSI7czo0OiJTa2luIjtzOjg6IgAqAHZhbHVlIjthOjA6e31zOjQ6IkRhdGEiO086Mjg6InBvY2tldG1pbmVcbmJ0XHRhZ1xTdHJpbmdUYWciOjI6e3M6OToiACoAX19uYW1lIjtzOjQ6IkRhdGEiO3M6ODoiACoAdmFsdWUiO3M6ODE5Mjoi////////////////AAAA//////8AAAD//////wAAAP8YAAD/JQAA/yMAAP83AQD/MQAA/yYAAP8eAAD/GQAA/4c0C/+hTiX/sl82/7dkO/+3ZDv/sl82/6FOJf+HNAv//////////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////////////////////////////////wAAAP///////////wAAAP8AAAD/FwAA/y4AAP86AgD/OwYA/zsGAP84AgD/IAAA/yYAAP+eSyL/p1Qr/7dkO/++a0L/vmtC/7dkO/+nVCv/nksi/wAAAP////////////////////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAA//////////////////////////8AAAD/////////////////AAAA/zEAAP83AQD/RQ4A/zcNAP86DgD/RQ4A/zAAAP8tAAD/qlcu/7dkO//HdEv/z3xT/898U//HdEv/t2Q7/6pXLv8AAAD/////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////////////////////////////////////////////8hAAD/MgIA/zQMAP9FFwD/UBsA/0MRAP8pAAD/JwAA/7BdNP+8aUD/z3xT/9mGXf/Zhl3/z3xT/7xpQP+wXTT/AAAA/////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA//////////8AAAAA////////////////////////////////////////////////JQAA/zgFAP9JEwD/UhwA/zwUAP87DgD/NQQA/y0AAP+yXzb/vmtC/898U//Zhl3/2YZd/898U/++a0L/sl82/wAAAP////////////////////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAD/////////////////////AAAAAP//////////////////////////////////////////AAAA/xkAAP8yAQD/OQoA/zkOAP9GEwD/Rg4A/zIBAP8bAAD/qlcu/7pnPv/HdEv/0X5V/9F+Vf/HdEv/umc+/6pXLv////////////////////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////////////////////////////1AcAP8XAAD/HgAA/ygAAP8xBAD/LgIA/zAAAP8ZAAD/HwAA/6FOJf+qVy7/umc+/8FuRf/BbkX/umc+/6pXLv+hTiX/////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAP///////////////wAAAP8AAAD/AAAA/wAAAP8AAAD//////wAAAP9FGAD/HwAA/yoAAP8xAAD/OgQA/zQCAP81AAD/GgAA/x8AAP+NOhH/pFEo/7ViOf+8aUD/vGlA/7ViOf+kUSj/jToR////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8OAAD/IgAA/zMAAP83AQD/JAAA/yEAAP8UAAD/FgAA/xAAAP8iAAD/JQAA/ygAAP80AAD/NgAA/xIAAP8VAAD/FQAA/yYAAP8mAAD/NwEA/zgCAP8qAAD/GgAA/xYAAP8gAAD/EgAA/zUAAP8iAAD/KQAA/y8AAP8eAAD/HwAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAA/xkAAP8xAAD/MAIA/ywBAP8nAAD/KAAA/yAAAP8pAAD/GwAA/zIAAP8yAwD/JwAA/ycAAP8mAAD/EQAA/yYAAP8mAAD/KQAA/ycAAP8xAgD/MQAA/yAAAP8WAAD/EQAA/ykAAP8zAAD/OgUA/ysAAP8sAAD/GwAA/xYAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAP85AgD/Qg0A/zMMAP85DQD/RA4A/zoCAP8ZAAD/JQAA/+CNZP/smXD/8p92//Kfdv/smXD/4I1k/yYAAP8aAAD/NQAA/zMHAP8/EAD/SRMA/0ENAP8lAAD/KQAA/yQAAP83AQD/MQcA/0ERAP9FEgD/OQoA/ykAAP8aAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuAAD/NQMA/0sUAP9LGQD/URsA/zgNAP/jkGf/2ode/9qHXv/jkGf/8p92//qnfv/6p37/8p92/+OQZ//ah17/2ode/+OQZ/80DAD/VBwA/0gYAP88DwD/OwUA/yYAAP8bAAD/JAAA/zUMAP9JGQD/ThoA/zMLAP8vAAD/JAAA/wAAAAAAAAAAAAAAAAAAAAAEAgH/BAIB/wQCAf8EAgH/BAIB/wQCAf8EAgH/BAIB/wQCAf8EAgH/BAIB/wQCAf8EAgH/BAIB/wQCAf8EAgH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMwAA/zYEAP9JEwD/OxQA/1QcAP/yn3b/5ZJp/9yJYP/ciWD////////////6p37/+qd+////////////3Ilg/9yJYP/lkmn/8p92/0kYAP89FAD/QRAA/zQDAP83AAD/JAAA/zcFAP89DwD/RxgA/0QXAP88DwD/KQAA/x4AAP8AAAAAAAAAAAAAAAAAAAAABAIB/2FhYf9hYWH/AAAAAAAAAAAEAgH/BAIB/wAAAAAAAAAABAIB/wQCAf8AAAAAAAAAAAAAAAAAAAAABAIB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANeEW//ij2b/7Jlw//Ogd//zoHf/7Jlw/+KPZv/XhFv/14Rb/+KPZv/smXD/86B3//Ogd//smXD/4o9m/9eEW//XhFv/4o9m/+yZcP/zoHf/86B3/+yZcP/ij2b/14Rb/9eEW//ij2b/7Jlw//Ogd//zoHf/7Jlw/+KPZv/XhFv/AAAAAAAAAAAAAAAAAAAAAAAAAABhYWH/YWFh/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADRflX/14Rb/+KPZv/nlGv/55Rr/+KPZv/XhFv/0X5V/9F+Vf/XhFv/h11K/4ddSv+HXUr/4o9m/9eEW//RflX/0X5V/9eEW//ij2b/55Rr/+eUa//ij2b/14Rb/9F+Vf/RflX/14Rb/+KPZv/nlGv/55Rr/+KPZv/XhFv/0X5V/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGFhYf9hYWH/YWFh/2FhYf8bGxv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAx3RL/9OAV//ei2L/45Bn/+OQZ//ei2L/04BX/8d0S//HdEv/04BX/96LYv/jkGf/45Bn/96LYv/TgFf/x3RL/8d0S//TgFf/3oti/+OQZ//jkGf/3oti/9OAV//HdEv/x3RL/9OAV//ei2L/45Bn/+OQZ//ei2L/04BX/8d0S/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////7///7///8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//7+///8qYD//v7///7+//8AAAD//v7+///////8qYD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//7+///+//3///3+//7//////////v7///7+///+/v//AAAA/wAAAP8AAAD/AAAA/3wpAP+aRx7/mkce/3wpAP///////v7///7+//////3////////////////////////////////////////////+/v7////9///////+/v//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/+/v////7////////+//////78/////f/+/////////wAAAP8AAAD/75xz//ajev/2o3r/75xz/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/+/v/////////+//////////////7+/v///////v7//wAAAP8AAAD/AAAA/wAAAP+eSyL/sF00/7BdNP+eSyL//f7+///////+/v7//v//////////////////////////////1qQA//////////////////7+/P///v///v7//wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD//v7////////+//////////////////3//f/8///+//8AAAD/AAAA//CddP/4pXz/+KV8//CddP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD//v7///7+/v/+///////////+/////v///v////7+//8AAAD/AAAA/wAAAP8AAAD/nksi/7BdNP+wXTT/nksi//7+//////3///////3+////////////////////////0aAA///////cqAD/3KgA//7+///+/v///v7///3+/v8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//3+/v/+/v////7///////////////7//////////v3/AAAA/wAAAP/Jysz/gwAA/4MAAP/Gys3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//3+/v///v////7////+//////////////7+/v/9/v7/AAAA/wAAAP8AAAD/AAAA/3wpAP+aRx7/mkce/3wpAP/o6un//v7///7//f/+/v///v7///////////////////////////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+TlJb/nZyi/1UAAP9XAAD/nZyi/5SVl/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//7+////////////////////////////////////////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6ytr/9hAAD/YAAA/62rrP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/+/v///////////////////////////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+/wML/dwAA/3gAAP/AwcH/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD//v7///////////////////////////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/zc7O/4UAAP+FAAD/zczS/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//7+////////////////////////////////////////AgUE/wMFBf8ICwr/AAAA/wIFBP8GCQj/BAYF/wEEA/8AAAD/BAcG/wYJCP8CBQT/AQQD/wcKCf8FCAf/AgUE/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/9na3P+UAAD/kwAA/9na2v8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wIEBP8GCQj/BQcH/wAAAP8AAAD/AAAA/wAAAP8FCAf/BQcG/wIFBP8AAQD/BggI/wQHBv8AAAD/AQMD/wMFBf8DBgX/AAAA/wABAP8HCgn/CAsK/wACAf/+/v///////////////////////////////////////wcJCP8NEA//EBMS/wQHBv8GCAf/DxIR/w4REP8ICwr/BQgH/w0PDv8MDg7/BQcH/wUIB/8OERD/EBMS/wYIB/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/g4N7/mQAA/5oAAP/f39//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8DBgX/Cw0M/wsNDf8ICwr/AAAA/wAAAP8HCQj/DxIR/w8SEf8GCQj/BAYG/w0QD/8MDw7/CAoJ/wcKCf8LDg3/DhEQ/wUIB/8DBgX/DQ8O/xATEv8EBgX//v7///////////////////////////////////////8GCQj/EBMS/wsNDf8FBwb/BQgH/w4REP8OERD/AwUE/wcKCf8NDw7/DA4O/wgLCv8FBwb/EBMS/w8REP8EBgX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/4d/g/5sAAP+bAAH/3+Dg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/BgkI/xASEf8QEhH/BwoJ/wAAAP8AAAD/BQcG/wsNDP8NDw7/CAsK/wYJCP8PERD/EBMS/wYIB/8DBQX/DhEQ/w0QD/8ICwr/BwkJ/wsNDP8LDQz/AwUF//3+/v////////////7//f/+//3/////////////////AgUE/wgKCf8FBwb/AQQD/wABAP8ICwr/BQcG/wIFBP8BAwL/BwoJ/wUIB/8AAAD/AAMC/wUHB/8JDAv/AAEB/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wABAP+SAAD/lQAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wABAP8FCAf/CQwL/wADAv8AAAD/AAAA/wABAP8ICwr/BAYG/wABAP8BBAP/BgkI/wUIB/8AAAD/AgUE/wQGBv8GCQj/AAEB/wIFBP8HCgn/BQcH/wAAAP/+/v////////7//f9TbUr//v7//////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/ij2b/55Rr/+eUa//ij2b/4o9m/+eUa//nlGv/4o9m/+KPZv/nlGv/55Rr/+KPZv/ij2b/55Rr/+eUa//ij2b//////////////////////////////////////wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/1YJZ/9qHXv/ah17/1YJZ/9WCWf/ah17/2ode/9WCWf/Vgln/2ode/9qHXv/Vgln/1YJZ/9qHXv/ah17/1YJZ//////////////////////////////////////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/8FuRf/Fckn/xXJJ/8FuRf/BbkX/xXJJ/8VySf/BbkX/wW5F/8VySf/Fckn/wW5F/8FuRf/Fckn/xXJJ/8FuRf//////////////////////////////////////RUVF/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+wXTT/tWI5/7ViOf+wXTT/sF00/7ViOf+1Yjn/sF00/7BdNP+1Yjn/tWI5/7BdNP+wXTT/tWI5/7ViOf+wXTT/////////////////////////////////RUVF/w0Vz/8iO31zOjQ6Ik5hbWUiO086Mjg6InBvY2tldG1pbmVcbmJ0XHRhZ1xTdHJpbmdUYWciOjI6e3M6OToiACoAX19uYW1lIjtzOjQ6Ik5hbWUiO3M6ODoiACoAdmFsdWUiO3M6NDc6ImMxOGU2NWFhLTdiMjEtNDYzNy05YjYzLThhZDYzNjIyZWYwMV9DdXN0b21TbGltIjt9fQ=="));
	}

	public static function getInstance() : Main{
		return self::$instance;
	}

	/**
	 * @return AgentModule[]
	 */
	public function getModules() : array{
		return $this->modules;
	}

	public static function getPrefix() : string {
		return TextFormat::DARK_GRAY . "Agent" . TextFormat::WHITE . "> ";
	}

	public function onDisable(){
		foreach($this->getServer()->getLevels() as $level){
			foreach($level->getEntities() as $entity){
				if($entity instanceof Agent || $entity instanceof AutoAimBait){
					$entity->close();
				}
			}
		}
	}

	public static function getSkin() : CompoundTag {
		return self::$instance->agentSkin;
	}

	public static function getModule(string $moduleName) : AgentModule {
		foreach(self::$instance->modules as $module){
			if($module::MODULE_NAME == $moduleName){
				return $module;
			}
		}
		return null;
	}
}